### ISSUE TITLE
Favicons do exist

### ISSUE THREAD

**Issue by vincentscode** [aarondiel/abi-website#1]
May i present to you the power of a favicon?

![image](https://user-images.githubusercontent.com/26576880/126822156-0741a6d7-22d1-4a31-b13c-2b5d4b2e3352.png)

You can steal this one from here https://www.sgg-bingen.de/templates/cirrus-yellow/favicon.ico or create your own one.

The file is that hast to be replaced is located at frontend/public/favicon.ico

**Comment by aarondiel** [comment]
the favicon was supposed to be implemented when the logo was discussed finished and i personally didn't care enough to add one
still, i wouldn't steal the icon because i'd end up being sued and the website should not be associated with the school it emerged from
the site now features a svg favicon for newer browsers and a 32 x 32 png fallback
(see #11985f31a47406f0ce5f5e1b358b26652cf228a6)

![favicon](https://user-images.githubusercontent.com/38919146/127849432-eb76795c-edb7-43f7-a3c9-d1026b03bd76.png)

the image might not render directly because favicons usually get cashed by the browser
